<?php

namespace Database\Seeders;

use App\Models\ServiceType;
use Illuminate\Database\Seeder;

class ServiceTypeSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'code' => 'L01',
                'slug' => 'rekomendasi-pengiriman-ppks',
                'name' => 'Surat Rekomendasi Pengiriman PPKS ke Panti/Yayasan Sosial',
                'description' => 'Rekomendasi pengiriman Pemerlu Pelayanan Kesejahteraan Sosial (Tuna Susila, PGOT, Korban Napza, ODHA, ODGJ) ke panti/yayasan sosial.',
                'requirements' => [
                    'Surat Pengantar/Permohonan dari Kepala Pekon/Lurah (proposal)',
                    'Terdaftar pada DTSEN desil 1-5',
                    'Fotokopi KTP, KK, dan foto PPKS',
                ],
                'procedure' => [
                    'Pemohon menyerahkan proposal ke Dinas Sosial',
                    'Kadis memerintahkan Kabid Rehsos melakukan peninjauan',
                    'Verifikasi dan monev terhadap calon PPKS',
                    'Petugas mengajukan draft surat rujukan',
                    'Pelaksanaan rujukan',
                ],
                'output' => 'Surat Rekomendasi Pengiriman PPKS',
                'bidang' => 'Rehsos',
                'sla_minutes' => 30 * 24 * 60,
                'sla_display' => '1 bulan / kondisional',
                'icon' => 'home-modern',
                'color' => 'primary',
                'is_featured' => false,
            ],
            [
                'code' => 'L02',
                'slug' => 'rekom-rehabilitasi-disabilitas',
                'name' => 'Rekomendasi Rehabilitasi Penyandang Disabilitas ke Balai Rehabilitasi Sosial',
                'description' => 'Surat rekomendasi penyandang disabilitas untuk mengakses Balai Rehabilitasi Sosial.',
                'requirements' => [
                    'Surat Pengantar/Permohonan dari Kepala Pekon/Lurah',
                    'Terdaftar DTSEN desil 1-5',
                    'Fotokopi KTP, KK, dan foto PPKS',
                ],
                'procedure' => [
                    'Pemohon menyerahkan surat pengantar',
                    'Petugas melakukan verifikasi dan validasi',
                    'Identifikasi dan verifikasi lapangan',
                    'Pembuatan surat rujukan',
                ],
                'output' => 'Surat Rekomendasi Rehabilitasi Penyandang Disabilitas',
                'bidang' => 'Rehsos',
                'sla_minutes' => 30,
                'sla_display' => '30 menit',
                'icon' => 'heart',
                'color' => 'primary',
                'is_featured' => true,
            ],
            [
                'code' => 'L03',
                'slug' => 'surat-tanda-terdaftar-lks',
                'name' => 'Surat Tanda Terdaftar Lembaga/Yayasan Sosial/Panti Asuhan',
                'description' => 'Penerbitan surat tanda terdaftar bagi Lembaga Kesejahteraan Sosial (LKS), yayasan, atau panti asuhan.',
                'requirements' => [
                    'AD/ART LKS', 'Surat keterangan domisili', 'Susunan kepengurusan LKS',
                    'Fotokopi akte notaris', 'NPWP',
                    'Surat terdaftar di Kemenkumham', 'Surat terdaftar di Kesbangpol Pringsewu',
                    'Fotokopi ijin operasional bagi LKS lama', 'Daftar identitas klien',
                    'Foto kantor sekretariat LKS',
                ],
                'procedure' => [
                    'Surat masuk dengan berkas lengkap',
                    'Petugas identifikasi & verifikasi lapangan',
                    'Pembahasan hasil verifikasi',
                    'Pembuatan surat tanda terdaftar / ijin operasional',
                    'Penyerahan dokumen ke pemohon',
                    'Monitoring dan evaluasi LKS',
                ],
                'output' => 'Surat Tanda Terdaftar LKS/Panti Asuhan',
                'bidang' => 'Linjamsos',
                'sla_minutes' => 4 * 8 * 60,
                'sla_display' => '4 hari kerja',
                'icon' => 'building-office',
                'color' => 'primary',
            ],
            [
                'code' => 'L04',
                'slug' => 'rekom-ugb-pub',
                'name' => 'Surat Rekomendasi UGB & PUB',
                'description' => 'Rekomendasi Undian Gratis Berhadiah (UGB) dan Pengumpulan Uang & Barang (PUB) untuk lembaga sosial.',
                'requirements' => [
                    'Surat permohonan bermaterai Rp 10.000',
                    'Akta pendirian & SK pengesahan (Badan Hukum/Usaha)',
                    'Surat kuasa & KTP penerima kuasa (jika dikuasakan)',
                    'Proposal lengkap penyelenggaraan',
                    'Fotokopi tanda daftar Yayasan/Organisasi/Lembaga',
                    'Fotokopi NIB',
                    'Izin lokasi pengumpulan',
                    'Fotokopi perjanjian sewa tempat (jika bukan milik sendiri)',
                ],
                'procedure' => [
                    'Pemohon datang dengan berkas lengkap',
                    'Verifikasi dan validasi lapangan',
                    'Pembuatan surat rekomendasi izin PUB',
                ],
                'output' => 'Surat Rekomendasi UGB & PUB',
                'bidang' => 'Linjamsos',
                'sla_minutes' => 3 * 8 * 60,
                'sla_display' => '3 hari kerja',
                'icon' => 'gift',
                'color' => 'primary',
            ],
            [
                'code' => 'L05',
                'slug' => 'pelayanan-lk3',
                'name' => 'Pelayanan Lembaga Konsultasi Kesejahteraan Keluarga (LK3)',
                'description' => 'Konsultasi dan pendampingan psikososial bagi keluarga yang mengalami permasalahan kesejahteraan.',
                'requirements' => [
                    'Surat Permohonan dari masyarakat/Pekon/Lurah/aparat penegak hukum',
                    'Fotokopi KTP, KK, dan foto PPKS',
                ],
                'procedure' => [
                    'Pemohon datang membawa Surat Permohonan',
                    'Petugas melakukan identifikasi masalah',
                    'Dinas berkoordinasi dengan tim profesi LK3',
                    'Pembuatan Surat Rujukan LK3',
                ],
                'output' => 'Layanan konsultasi dan pendampingan psikososial',
                'bidang' => 'Rehsos',
                'sla_minutes' => 7 * 8 * 60,
                'sla_display' => '7 hari kerja / kondisional',
                'icon' => 'chat-bubble-left-right',
                'color' => 'primary',
            ],
            [
                'code' => 'L06',
                'slug' => 'rekom-bpjs',
                'name' => 'Surat Rekomendasi Pendaftaran BPJS (PBI JK)',
                'description' => 'Surat rekomendasi pendaftaran BPJS Kesehatan jalur Penerima Bantuan Iuran (PBI).',
                'requirements' => [
                    'Surat Keterangan Tidak Mampu (SKTM) dari desa/kelurahan',
                    'Surat Keterangan Sakit dari dokter',
                    'Fotokopi KTP & KK',
                    'Foto PPKS', 'Foto rumah',
                ],
                'procedure' => [
                    'Berkas diserahkan oleh aparatur pekon/Puskesos/pendamping sosial',
                    'Verifikasi dan identifikasi kelengkapan berkas',
                    'Penerbitan Surat Rekomendasi',
                    'Petugas mengirim ke BPJS via elektronik',
                ],
                'output' => 'Surat Rekomendasi Pendaftaran PBI JK',
                'bidang' => 'Linjamsos',
                'sla_minutes' => 30,
                'sla_display' => '30 menit',
                'icon' => 'shield-check',
                'color' => 'primary',
                'is_featured' => true,
            ],
            [
                'code' => 'L07',
                'slug' => 'rehsos-disabilitas-terlantar',
                'name' => 'Rehabilitasi Sosial Penyandang Disabilitas Terlantar',
                'description' => 'Rehabilitasi bagi penyandang disabilitas terlantar tanpa keluarga atau yang membutuhkan perlindungan.',
                'requirements' => [
                    'Surat Permohonan Pekon/Kelurahan mengetahui Camat',
                    'Fotokopi KTP (untuk usia >17 tahun)',
                    'Fotokopi KK',
                ],
                'procedure' => [
                    'Pemohon datang membawa Surat Permohonan',
                    'Petugas verifikasi & validasi laporan',
                    'Asesmen awal',
                    'Identifikasi & penjangkauan',
                    'Pengajuan draft surat rujukan ke Kadis',
                ],
                'output' => 'Surat Rekomendasi/Usulan Rehsos Penyandang Disabilitas Terlantar',
                'bidang' => 'Rehsos',
                'sla_minutes' => 8 * 60,
                'sla_display' => '1 hari kerja',
                'icon' => 'user-group',
                'color' => 'primary',
                'is_featured' => true,
            ],
            [
                'code' => 'L08',
                'slug' => 'bantuan-sosial-tak-terduga',
                'name' => 'Bantuan Sosial Tak Terduga (BTT) Warga Miskin',
                'description' => 'Bantuan sosial bagi warga miskin/tidak mampu yang menghadapi kondisi tak terduga (mis. sakit kronis, musibah).',
                'requirements' => [
                    'Surat Permohonan Pekon/Kelurahan mengetahui Camat (ke Bupati c.q Kadis)',
                    'Fotokopi KTP', 'Fotokopi KK', 'Foto rumah', 'Foto pasien',
                    'Surat Keterangan Medis/Fasilitas Kesehatan',
                ],
                'procedure' => [
                    'Berkas masuk via aparatur pekon/Puskesos/pendamping',
                    'Verifikasi & identifikasi surat',
                    'Penjangkauan, verifikasi & identifikasi PPKS',
                    'Penerbitan Nota Dinas ke Bupati',
                    'Pencairan bantuan non-tunai',
                    'Monitoring & pelaporan penggunaan dana',
                ],
                'output' => 'Dokumen rekomendasi/usulan BTT',
                'bidang' => 'Linjamsos',
                'sla_minutes' => 30 * 8 * 60,
                'sla_display' => '30 hari kerja',
                'icon' => 'banknotes',
                'color' => 'primary',
            ],
            [
                'code' => 'L09',
                'slug' => 'bantuan-sosial-terencana',
                'name' => 'Pelayanan Bantuan Sosial Terencana',
                'description' => 'Bantuan sosial terencana (mis. bantuan biaya pendidikan KIP) bagi keluarga kurang mampu.',
                'requirements' => [
                    'Surat pengantar/permohonan Pekon/Lurah',
                    'Fotokopi KTP & KK',
                    'Kartu Indonesia Pintar (KIP)',
                    'Foto rumah',
                    'Rancangan Anggaran Biaya',
                ],
                'procedure' => [
                    'Surat masuk dengan berkas lengkap',
                    'Identifikasi masalah klien & pemeriksaan berkas',
                    'Verifikasi terhadap usulan penerima',
                ],
                'output' => 'Bantuan biaya pendidikan untuk siswa keluarga kurang mampu',
                'bidang' => 'Linjamsos',
                'sla_minutes' => 14 * 8 * 60,
                'sla_display' => 'Kondisional',
                'icon' => 'academic-cap',
                'color' => 'primary',
            ],
            [
                'code' => 'L10',
                'slug' => 'pengaduan-masyarakat',
                'name' => 'Pelayanan Pengaduan Masyarakat',
                'description' => 'Kanal pengaduan masyarakat terkait pelayanan sosial.',
                'requirements' => [
                    'Melapor ke Dinas Sosial Kabupaten Pringsewu',
                    'Atau menghubungi Call Center 0822-6986-7911',
                ],
                'procedure' => [
                    'Pemohon menyampaikan aduan',
                    'Petugas pengaduan melakukan identifikasi',
                    'Penyampaian solusi atas aduan',
                ],
                'output' => 'Kanal untuk masyarakat menyampaikan keluhan/aspirasi & penyelesaian',
                'bidang' => 'Sekretariat',
                'sla_minutes' => 3 * 8 * 60,
                'sla_display' => 'Kondisional',
                'icon' => 'megaphone',
                'color' => 'warning',
                'is_featured' => true,
            ],
            [
                'code' => 'L11',
                'slug' => 'rehsos-anak-terlantar',
                'name' => 'Pelayanan Rehabilitasi Sosial Anak Terlantar',
                'description' => 'Penanganan dan rehabilitasi sosial bagi anak terlantar.',
                'requirements' => [
                    'Surat Permohonan dari Pekon/Kelurahan',
                    'Akta Kelahiran (jika ada)',
                    'Fotokopi KTP & KK (jika ada)',
                    'Foto PPKS',
                ],
                'procedure' => [
                    'Pemohon melapor via call center / datang langsung',
                    'Verifikasi & monev atas laporan',
                    'Koordinasi dengan Satuan Bakti Pekerja Sosial Anak Kemensos',
                    'Penjangkauan dan penanganan tim',
                ],
                'output' => 'Penampungan, perlindungan sementara, bantuan sandang/pangan/papan, pendampingan psikososial',
                'bidang' => 'Rehsos',
                'sla_minutes' => 8 * 60,
                'sla_display' => '1 hari kerja / kondisional',
                'icon' => 'sparkles',
                'color' => 'primary',
            ],
            [
                'code' => 'L12',
                'slug' => 'surat-keterangan-dtsen',
                'name' => 'Surat Keterangan Terdaftar DTSEN',
                'description' => 'Surat keterangan resmi yang menyatakan bahwa Anda terdaftar dalam Data Terpadu Sosial Ekonomi Nasional.',
                'requirements' => [
                    'Surat Permohonan dari Kepala Pekon/Kelurahan (atau ditujukan ke Kadis)',
                    'Fotokopi KTP (untuk usia >17 tahun)',
                    'Fotokopi KK',
                ],
                'procedure' => [
                    'Berkas diserahkan oleh aparatur pekon/Puskesos/pendamping/keluarga',
                    'Verifikasi & identifikasi kelengkapan berkas',
                    'Penerbitan Surat Keterangan DTSEN ber-barcode',
                    'Penyerahan surat ke pemohon',
                ],
                'output' => 'Surat Keterangan Terdaftar DTSEN',
                'bidang' => 'Linjamsos',
                'sla_minutes' => 15,
                'sla_display' => '15 menit',
                'icon' => 'identification',
                'color' => 'primary',
                'is_featured' => true,
            ],
            [
                'code' => 'L13',
                'slug' => 'orang-terlantar-kehabisan-bekal',
                'name' => 'Orang Terlantar dan Kehabisan Bekal',
                'description' => 'Bantuan reunifikasi/pemulangan untuk warga terlantar atau kehabisan bekal di luar daerah.',
                'requirements' => [
                    'Fotokopi KTP dan/atau KK (jika ada)',
                    'Surat Keterangan Terlantar dari Kepolisian',
                ],
                'procedure' => [
                    'Pelapor datang ke Dinas Sosial (setelah ke kepolisian)',
                    'Petugas menerima & verifikasi awal',
                    'Koordinasi reunifikasi dengan keluarga jika diketahui',
                    'Penerbitan draft surat pemulangan',
                    'Intervensi pemulangan',
                    'Pemulangan berjenjang via Dinsos Provinsi/Kab. lain bila perlu',
                ],
                'output' => 'Dokumen rekomendasi reunifikasi/pemulangan',
                'bidang' => 'Rehsos',
                'sla_minutes' => 8 * 60,
                'sla_display' => '1 hari kerja',
                'icon' => 'truck',
                'color' => 'primary',
            ],
            [
                'code' => 'L14',
                'slug' => 'kie-konseling-kampanye',
                'name' => 'KIE, Konseling, dan Kampanye Sosial PPKS',
                'description' => 'Komunikasi, Informasi & Edukasi (KIE), konseling, dan kampanye sosial khususnya untuk PGOT.',
                'requirements' => [
                    'Pengaduan/kiriman/penjangkauan PGOT psikotik & non-psikotik',
                    'Dari masyarakat / Aparatur Pekon-Lurah / SDM Kesos',
                ],
                'procedure' => [
                    'PGOT diserahkan ke Dinas Sosial',
                    'Dinas Sosial melakukan asesmen',
                    'Intervensi sesuai hasil asesmen',
                ],
                'output' => 'Rekomendasi Rehabilitasi PGOT, layanan KIE, layanan reunifikasi',
                'bidang' => 'Rehsos',
                'sla_minutes' => 3 * 8 * 60,
                'sla_display' => '3 hari kerja',
                'icon' => 'speaker-wave',
                'color' => 'primary',
            ],
            [
                'code' => 'L15',
                'slug' => 'rehsos-lansia-terlantar',
                'name' => 'Rehabilitasi Sosial Bagi Lanjut Usia Terlantar',
                'description' => 'Penanganan rehabilitasi sosial bagi lanjut usia terlantar.',
                'requirements' => [
                    'Surat permohonan Pekon/Kelurahan mengetahui Camat ke Kadis',
                    'Fotokopi KK dan/atau KTP (jika ada)',
                    'Kartu KIS (jika ada)',
                    'Foto lansia bersangkutan',
                ],
                'procedure' => [
                    'Berkas masuk via aparatur pekon/Puskesos/pendamping',
                    'Verifikasi berkas',
                    'Penjangkauan, verifikasi & identifikasi',
                    'Penerbitan Surat Rekomendasi Rehsos Lansia',
                    'Pengiriman ke panti rehabilitasi sosial lansia',
                ],
                'output' => 'Surat Rekomendasi & pengiriman ke Panti Rehabilitasi Sosial',
                'bidang' => 'Rehsos',
                'sla_minutes' => 15 * 8 * 60,
                'sla_display' => '15 hari kerja',
                'icon' => 'user',
                'color' => 'primary',
            ],
            [
                'code' => 'L16',
                'slug' => 'rekom-cota',
                'name' => 'Surat Rekomendasi Calon Orang Tua Asuh (COTA)',
                'description' => 'Surat rekomendasi proses pengangkatan anak (COTA) ke Dinsos Provinsi Lampung.',
                'requirements' => [
                    'Calon anak angkat: usia <18 tahun, terlantar/diterlantarkan, butuh perlindungan',
                    'Calon ortu angkat: sehat jasmani-rohani, usia 30-55 tahun, sah menikah min. 5 tahun',
                    'Surat pernyataan kepentingan terbaik anak',
                ],
                'procedure' => [
                    'Pemohon datang dengan kelengkapan dokumen',
                    'Verifikasi awal berkas',
                    'Petugas registrasi & laporkan ke Kadis',
                    'Disposisi ke Kabid/Kasi terkait',
                    'Home visit bersama Sakti Peksos Anak',
                    'Pembuatan laporan sosial kelayakan COTA',
                    'Draft surat rekomendasi ke Dinsos Provinsi',
                ],
                'output' => 'Surat Rujukan Proses Pengangkatan Anak',
                'bidang' => 'Rehsos',
                'sla_minutes' => 15 * 8 * 60,
                'sla_display' => '15 hari kerja',
                'icon' => 'users',
                'color' => 'primary',
            ],
        ];

        foreach ($services as $index => $service) {
            ServiceType::create(array_merge($service, [
                'is_active' => true,
                'order_no' => $index + 1,
                'is_featured' => $service['is_featured'] ?? false,
            ]));
        }
    }
}
